version: '3.8'

services:
  lmstudio:
    shm_size: '8gb'
    build: 
      dockerfile: Dockerfile
      context: .
      shm_size: '8gb'
    devices:
      - nvidia.com/gpu=all
    container_name: lmstudio
    ports:
      - "1234:1234"
      - "5900:5900"
    volumes:
      - /root/development/OllamaToGGUF/Output/models:/root/.cache/lm-studio/models
      - /root/development/OllamaToGGUF/Output:/root/docs
    environment:
      - CONTEXT_LENGTH=32768
    command: ["/start_services.sh"]
    restart: always